language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
script:
  - python setup.py test
notifications:
  email: false