
  name: arcanum
  version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: An encryption manager # 79 char long summary
  description: |
    Arcanum is a tool for handling encryption. Generate/store passwords in a database
    of your choice, encrypt notes and store them there too.
    Handle keys and asymmetric stuff.
    STILL IN THE WORKS!
  architectures:
    - amd64
  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
  
  apps:
    arcanum:
      command: python3 ./index.py

  parts:
    arcanum:
      plugin: python
      python-version: python3
      source: ./arcanum
      python-packages:
        - mysql-connector
        - PyQt5
        - sip
        - python-gnupg
        - QtAwesome
        - QtPy
        - six
        - pytest
